<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MicroGrid.Bot-286c0094-379d-417c-8afc-4e92b12688c7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JK.OKX.Net" Version="4.14.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroGrid.Application\MicroGrid.Application.csproj" />
  </ItemGroup>
</Project>
